---
title: "Ethics and Reflexivity & Peer Review Project"
subtitle: "MY400 Week 7: The Fundamentals of Research Design"
author: Zach Dickson, PhD 
institute: London School of Economics
bibliography: references.bib
format:
  revealjs: 
    fontsize: 1.5em
    logo: images/LSE_logo.png
    embed-resources: true
    slide-number: true
    preview-links: auto
    transition: fade
    code-fold: true
    citation_package: biblatex
    transition-speed: fast
    theme: [simple, custom.scss]
    footer: <a>Week 7 MY400 Seminar<br>Slides are available on Github ([z-dickson/MY400](https://github.com/z-dickson/MY400))</a>
---


# Questions from the Lecture?




# Peer Review Project 

*One of the most important skills in academia is the ability to provide constructive feedback to your peers. This is a skill that you will need to develop throughout your academic career. This week, you will have the opportunity to practice this skill by providing feedback on your peers' research proposals.*

- Groups of 2-3 students
  - Try to pair up with someone who is not already familiar with your work
- Use peer review criteria to evaluate each other's work
- Provide the feedback in a written form to the author 
- **Be constructive, be specific, and be kind**


# Peer Review Criteria


**Research problem**

- How is the problem motivated in the research?  
- How does the author demonstrate interest in the research problem?  
- Does the author clearly identify a puzzle or tension on the research question?   


# Peer Review Criteria

**Literature review:**

- Does the author clearly identify relevant bodies of literature? 
- Is existing literature synthesised in a way that sheds light on the existing arguments, positions and traditions or is it merely a list of publications?



# Peer Review Criteria

**Positioning/originality:**

- In what ways is/are the gap/s in knowledge clearly addressed?
- Does the author make a clear case for the originality of the research?


# Peer Review Criteria

**Research question**

- Is the research question clearly formulated?
- Does the question “naturally” follow from the research problem and literature review?
- Is it formulated in a way that matches the objectives of the project? 


# Peer Review Criteria

**Overall coherence** 

- How coherent is the project outline as a whole?   
- Does the research question align with the issues/actors/concepts of the research problem and literature? 

# Peer Review Project Worksheets 

# Research Ethics

*Ethics, Reflexivity, and “Ethically Important Moments” in Research* (Guillemin & Gillam, 2004)


# Research Ethics

*Ethics, Reflexivity, and “Ethically Important Moments” in Research* (Guillemin & Gillam, 2004)


- How and why do Guillemin and Gillam distinguish between ‘procedural ethics’ and ‘ethics in practice’?
  - What is the significance of this distinction? What common ground do these two approaches share? 


# Research Ethics

*Ethics, Reflexivity, and “Ethically Important Moments” in Research* (Guillemin & Gillam, 2004)


- According to Guillemin and Gillam, what is microethics? 
  - How does microethics relate to ethics in practice? 



# Research Ethics



*Ethics, Reflexivity, and “Ethically Important Moments” in Research* (Guillemin & Gillam, 2004)

- How does the position of subjects in medical research differ from the role of participants in qualitative research in ways that are ethically relevant?



# Seminar Activity – Ethical Dilemmas in Qualitative Research 

<br>

*Your research report on women’s feelings about with their home/work life balance has been picked up by one of the national papers. Your research showed that many women were dissatisfied with the way the workplace was unable to cope with their home demands and recommended structural changes within places of employment, but the article makes it sound as if you’re arguing that women should think twice about becoming involved in the workforce.*

<br>

- To what extent are you responsible for their interpretation? 
  - What could you do about it? 



# Seminar Activity – Ethical Dilemmas in Qualitative Research 

<br>

*You are undertaking social media research on politicians’ use of Twitter. You know several of the politicians personally due to your previous work in the civil service.*

<br>

- Do you need to get their informed consent?  Why or why not?   

- Do your personal relationships impact this decision?  

- Would the answer change if you were looking at a different social media platform, such as Facebook?  




# Next week - Week 8 

- Case studies and comparisons
- Office hours will be on Thursday 11-1300


# Thanks! 



# References

<div id="refs"></div>


